name: Run python wrtie on chat

on:
  push:
  schedule:
  # 定时任务，在每天的5点
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: pip_install_selenium
      run:
        pip install selenium

    - name: run_exe
      run: 
        python attack.py
